### ISSUE TITLE
Add version nubmers?

### ISSUE THREAD

**Issue by ofseed** [rbong/flog-symbols#1]
Thank you very much for creating these symbols, they are very useful. Would you mind adding tags for versions so we can package them more easily to repositories like Nixpkgs or AUR?

**Comment by rbong** [comment]
Thanks for the suggestion, I just pushed up `v1.0.0`

**Comment by ofseed** [comment]
Seems that there are no tags yet. Could you please try `git push --tags` again?

**Comment by rbong** [comment]
Sorry about that, should be pushed now.
